name: 🚀 Feature Request
description: Suggest a new feature or enhancement for OpenMineral
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the project roadmap and technical vision
          required: true
        - label: This feature aligns with the project's goals
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which component would this feature affect?
      options:
        - Trading Operations
        - AI/ML Integration
        - Market Analysis
        - Risk Management
        - Compliance/KYC
        - Workflow Automation
        - User Interface
        - API/Backend
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for adoption
        - Urgent - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current pain point?
      placeholder: "Currently, users have to manually..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like to see a feature that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Alternative approaches could include..."

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: What type of user would benefit from this feature?
      options:
        - Trader
        - Risk Manager
        - Compliance Officer
        - Market Analyst
        - Operations Manager
        - IT Administrator
        - All Users
        - Other
    validations:
      required: true

  - type: textarea
    id: business_value
    attributes:
      label: Business Value
      description: What business value would this feature provide?
      placeholder: "This feature would save X hours per day, reduce risk by Y%, improve efficiency by Z%..."

  - type: textarea
    id: technical_requirements
    attributes:
      label: Technical Requirements
      description: Are there any specific technical requirements or constraints?
      placeholder: "This feature should integrate with existing APIs, support real-time updates, handle high volume..."

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How would you measure the success of this feature?
      placeholder: "Feature is successful if users can accomplish X in Y time with Z accuracy..."

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Few hours to implement
        - Medium - Few days to implement
        - Complex - Few weeks to implement
        - Very Complex - Few months to implement
        - Unsure

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, screenshots, or examples of similar features

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request