apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # These values need to be base64 encoded
  # Example: echo -n 'postgresql://user:pass@host:5432/db' | base64
  postgresql-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9vcGVubWluZXJhbA==
  mongodb-url: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ29kYjowL29wZW5taW5lcmFs
  redis-url: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=